name             'rabbitmq-config'
maintainer       'Ride Share Market'
maintainer_email 'systemsadmin@ridesharemarket.com'
license          'All rights reserved'
description      'Installs/Configures rabbitmq-config'
long_description 'Installs/Configures rabbitmq-config'
version          '0.1.0'

depends 'secrets'
depends 'rabbitmq'
