name             'ssh-config'
maintainer       'Ride Share Market'
maintainer_email 'systemsadmin@ridesharemarket.com'
license          'All rights reserved'
description      'Installs/Configures ssh-config'
long_description 'Installs/Configures ssh-config'
version          '0.1.0'
