name             'logstash'
maintainer       'Ride Share Market'
maintainer_email 'systemsadmin@ridesharemarket.com'
license          'All rights reserved'
description      'Installs/Configures logstash'
long_description 'Installs/Configures logstash'
version          '0.1.0'

depends 'apt'
depends 'secrets'
