name             'apt-get-periodic'
maintainer       'Ride Share Market'
maintainer_email 'systemsadmin@ridesharemarket.com'
license          'All rights reserved'
description      'Installs/Configures apt-get-periodic'
long_description 'Installs/Configures apt-get-periodic'
version          '0.1.0'
