name             'docker-containers'
maintainer       'Ride Share Market'
maintainer_email 'systemsadmin@ridesharemarket.com'
license          'All rights reserved'
description      'Installs/Configures docker-containers'
long_description 'Installs/Configures docker-containers'
version          '0.1.0'
