name             'elasticsearch'
maintainer       'Ride Share Market'
maintainer_email 'systemsadmin@ridesharemarket.com'
license          'All rights reserved'
description      'Installs/Configures elasticsearch'
long_description 'Installs/Configures elasticsearch'
version          '0.1.0'
