name             'metrics'
maintainer       'Ride Share Market'
maintainer_email 'systemsadmin@ridesharemarket.com'
license          'All rights reserved'
description      'Installs/Configures metrics'
long_description 'Installs/Configures metrics'
version          '0.1.0'

depends 'graphite-config'
depends 'statsdaemon-bitly'
